apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: mynginxcustom
  name: mynginxcustom
  namespace: nginxcustom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mynginxcustom
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mynginxcustom
    spec:
      containers:
      - image: 618959785907.dkr.ecr.eu-west-1.amazonaws.com/nginxcustom:10
        name: nginxcustom
        ports:
        - containerPort: 80
        resources: {}
status: {}
